### ISSUE TITLE
Multistream Audio Player stream not working on Echo Dot gen 2 and lower

### ISSUE THREAD

**Issue by sholkayvishal** [alexa/skill-sample-nodejs-audio-player#145]
I made a podcast skill and It is working fine on Echo Dot Generation 3 and Spot and show,  but it is not working on any echo dot gen 2 and lower. The skill is working fine on Amazon Alexa Mobile App too.

**Comment by PMR1158** [comment]
You're probably wasting your time posting a question on here since there have been no answers posted in a month. It's no better over on the Alexa forum either - worst support network I ever saw. I've been searching for a resource where you can actually get some answers about Alexa Audio Player, if you happen to find one please let me know... Thanks

**Comment by JohnKavanagh1050** [comment]
I'm getting same issue stream plays then cuts out after a second on the echo dot v1. Anyone know the issue for this?

**Comment by scrudge** [comment]
@JohnKavanagh1050 I have the same issue.  Did you resolve  yours?

**Comment by JohnKavanagh1050** [comment]
Hey Larry i worked on this over a year ago but afaik i did fix it. here's my play function its in JS.
const StartPlaybackHandler = {
    async canHandle(handlerInput) {
       // const playbackInfo = await getPlaybackInfo(handlerInput);
        const request = handlerInput.requestEnvelope.request;
    },
    handle(handlerInput) {
        return controller.playLive(handlerInput);
    },
};

Hope this helps you.

**Comment by aszk** [comment]
The issue came from old version. We recreated this sample. If you still have the same issue, feel free to [contact us](alexa.design/contactus)
