### ISSUE TITLE
Getting the Error AudioPlayer is currently an unsupported namespace

### ISSUE THREAD

**Issue by brolinuk** [alexa/skill-sample-nodejs-audio-player#151]
Sorry that I borrowed this title from a closed ticket. I know the test can only be run on the device. However, but my Alex device has no response to the invocation name. 

I am wondering whether this audio player is actually supported out side US, as I am from the UK. 

Please help either wise. Thanks

**Comment by bigbeemerbiker** [comment]
Was this question ever answered? Here I am two years later with the same question. As with brolinuk, I get that it won’t work in the Developer Console (why, btw?) but I get nothing running it on my Echo. Is it US-only supported? I am U.K. and I found that Dabble Labs sample audio player skill from GitHub wouldn’t even install as as skill in my Developer Console unless I selected English-US instead of English-UK. Any suggestions much appreciated. I need to be able to get an Audio player skill working for my 100-year old mother, for whom Echo/Alexa is a lifeline.

**Comment by bigbeemerbiker** [comment]
OK, I feel bit foolish. Though it took me a long time to find it, my error was one that others have frequently pointed out as being the most common problem, namely that the mp3 file I was asking the AudioPlayer to play was not properly served. When I switched to sourcing the mp3 from a WordPress site of mine instead of Amazon S3 with the PresignedUrl function it worked! On an Echo device, that is. As others have pointed out, it won't work in the Developer Console. So problem solved!

**Comment by aszk** [comment]
Currently this repository supports only en-US. (This has only en-US interaction model) However you can create en-GB interaction model and it should work. 
https://developer.amazon.com/en-US/docs/alexa/custom-skills/add-additional-locales-of-the-same-language-to-your-custom-skills.html
