### ISSUE TITLE
Audio Player Skill on Alexa Companion App

### ISSUE THREAD

**Issue by nikhilm19** [alexa/skill-sample-nodejs-audio-player#153]
The audio player card preview shown in the notifications bar of mobile phone doesn't respond to button touches and the skill doesn't play next track and respectively.

**Comment by mfizz1** [comment]
> The audio player card preview shown in the notifications bar of mobile phone doesn't respond to button touches and the skill doesn't play next track and respectively.

This is because there is a problem with the code. The next previous and play correspond to a variation of `play` function. Play function has "speak" response builder, therefore it would throw a error along the lines of cannot send speak with this directive or command. To get around this, either remove speak from play function, or add a check for spoken command versus touch command

**Comment by aszk** [comment]
I think this is not relevant to the current code. I am going to close this but please let me know if this is still relevant to our sample code.
