### ISSUE TITLE
Unable to Safely Update Episode List

### ISSUE THREAD

**Issue by woodlandh** [alexa/skill-sample-nodejs-audio-player#3]
Hi Alexa team,

Issue:
- adding new episodes to the front of the audioData list breaks saved DynamoDB user data, as their in-progress episode is now incorrect
- adding new episodes to the end of the audioData list means that new users listen to the oldest episode by default, not the newest

First, I propose that we reverse audoData to be oldest-to-newest.

Second, if Attributes is not defined (new listener), the user should start on the last index of audioData instead of the first.

I haven't tested this, and I'm concerned about the use-case in which a listener has heard all episodes but not the latest. If I can think of a smooth implementation I'll submit a PR. On that note, I'm considering storing the audioData in DynamoDB for ease of updating, if that's of interest.

Great sample, thanks for getting me started on the new audio streaming feature!

~ Woodland

**Comment by mdusing** [comment]
@woodlandh I had a similar issue. I am wanting to continually add new episodes of my podcast to the skill. So in order to do this I need to add a new episode and update weekly.

No problem but it breaks the saved data. To solve this after the table is already created I added more items (50) to the playOrder List. See the method described here: https://github.com/alexa/skill-sample-nodejs-audio-player/issues/32

Secondly, I too agree that in the content of numbered episodes saying Previous and getting a higher number can be confusing to the user. I reversed the audio data as you described to be from oldest-to-newest.

I do like that one first open a new user is presented with the first episode playing. However, after resuming an episode I have now set it so that If you say No to resuming the episode you were playing the user is taken to the newest episode. unfortunately, this is manual and will need to be updated every time I add a episode.

I did this by changing the "Reset to top of the playlist when reached end." items in statehandlers.js In my case I changed them from 0 to 16 as I have 17 episodes and the playOrder List starts with 0.

If you or anyone knows of a way to set this dynamically let me know. Thanks and hope that helps.

PS this was a great starting point for our podcast app and provides a solid base.
