### ISSUE TITLE
Unable to set more then two audio URLs

### ISSUE THREAD

**Issue by BoardRockerz** [alexa/skill-sample-nodejs-audio-player#32]
Is there a possibility to integrated more than just two audio urls? I always get an "missing endpoint" issue when there is more then two audio urls (episode).

**Comment by mdusing** [comment]
I had this issue as well. The short answer is that the DynamoDB table is created the first time you run the skill in testing. So when it was created the DynamoDB Table playOrder List only had two items.

To fix:

This go to DynamoDB in the Amazon Console.
Select Tables on the left vertical menu.
Select LongFormAudioSample in the center list.
Select the Items tab.
Select the item from the center table by clicking the name under userId (there should only be one)
In the Edit Item pop up, click the arrow next to MmapAttr to expand
Scroll down to playOrder, expand that section
Then add more by clicking the + and choosing append after the last item

I had to repeat this and type the number every time. I added up to 50 so I wouldn't have to update it again for the future. The number next to playOrder List is the total items in the play order. I was able to loop fine between the first and last item event though I only had 17 items in the audioAssets.js and 50 items in the playOrder List.

Hope that helps. If anyone knows how to do this automatically without having to manually add more playOrder items please let me know.

**Comment by mdusing** [comment]
Unfortunately, this only works for the created user. Every time a new user starts the app for the first time a new Item is created in the DynamoDB table. I need to figure out how to update each user item with the new playOrder on load.

I believe this is best achieved by using the AWS api.

**Comment by govindbalki2105** [comment]
mdusing  thanks very much. I figured out the next step. In stateHandlers.js replace 

this.attributes['playOrder'] = Array.apply(null, {length: audioData.length}).map(Number.call, Number);

with 

this.attributes['playOrder'] = Array.apply(null, {length: 10}).map(Number.call, Number);

Goes without saying that the 10 could be any number. Also you'll have to delete the old DynamoDB table.

Thanks for your post! Hope this helps!

**Comment by nickyfoto** [comment]
I tried these suggestions but they didn't work for me. dynamodb was alway reset back to playlist [0, 1], haven't found a mechanism to prevent this from happening.

**Comment by baynado** [comment]
Thank you govindbalki2105! It works very well for my issue.

**Comment by sebsto** [comment]
Thank you for helping @govindbalki2105

**Comment by bhaskargara** [comment]
I am not able to find the stateHandlers.js

**Comment by sebsto** [comment]
We simplified the multi stream example by consolidating all the code in one single source file : index.js 

--Seb

**Comment by PMR1158** [comment]
Greetings Sébastien,

Just wondering why you're no longer responding to open issues with the
Alexa audio player template on GitHub? I've created an audio player skill
that's an overview of the Apollo moon missions from the 1970's but am
experiencing several issues I can't figure out. Some expert advice would be
greatly appreciated if you have the time.

https://github.com/alexa/skill-sample-nodejs-audio-player/issues/143
https://github.com/alexa/skill-sample-nodejs-audio-player/issues/142

Regards,
Paul Rimel

**Comment by sebsto** [comment]
Hello Paul,

Indeed, I took over another role at Amazon on January, and since then, my
daily activities and duties are not giving me enough time to continue to
actively maintain this code sample.  Please reach out to the Alexa
developer forum to get help.  I hope someone from Alexa developer advocate
team will be able to continue to provide support here.

Seb

**Comment by PMR1158** [comment]
OK Seb, thanks for the response! I've tried to get help on the developer
forum several times but to no avail. One of the Amazon folks there kept
saying he was testing my code but eventually claimed he couldn't reproduce
the issue using the sample code without any changes. So he told me to roll
back any changes I'd made & it should work fine but unfortunately it didn't
because I'd only changed the number of tracks and the speech prompts.
Anyway, I'll keep trying because I'd really like to get this skill working
and certified in time for the 50'th anniversary of the Apollo 11 moon
landing this July. Would you know anyone specifically I could try and reach
out to for help?

Cheers,
Paul
