### ISSUE TITLE
The remote endpoint could not be called when testing

### ISSUE THREAD

**Issue by tombrown08** [alexa/skill-sample-nodejs-audio-player#34]
Im doing this on Windows and have gone through this word for word but when I test in the Service simulator this error comes up "The remote endpoint could not be called, or the response it returned was invalid." any reasons why this is happening? im starting to think its not possible to do it on windows as ive also struggled building a rss feed skill and same outcome. If someone can get back to me as soon as possible it would be much appreciated

**Comment by BoardRockerz** [comment]
On a pc I failed too. Only on a mac everythings works fine.

Because this "code" is not a "windows code":
git clone https://github.com/alexa/skill-sample-nodejs-audio-player.git
cd skill-sample-nodejs-audio-player/js
npm install
zip -r ../audio-player.zip *

You need to switch this to DOS or whatever it like to call.

**Comment by n2questdev** [comment]
I tried exact same thing as you suggested @BoardRockerz... still I get "The remote endpoint could not be called, or the response it returned was invalid." Please suggest.

Does it makes sense to combine all handlers code into one index.js file? and paste it in the inline editor rather than uploading as zip artifact? 

I chose Node.js 4.3 and rest of the steps as exactly in the readme.

**Comment by winstonquin** [comment]
How do you convert the Git clone to DOS?

**Comment by arnianantha** [comment]
I am getting the same error. I zipped the JS folder contents and still no luck. anyone solved this?

**Comment by delwilliams** [comment]
Mine is not working either. I don't think it works on PCs which is interesting.

**Comment by annasxu** [comment]
I have a mac and I'm getting the same error.

**Comment by sebsto** [comment]
What is the command producing this error message ?
("The remote endpoint could not be called, or the response it returned was invalid.") 

This error message is delivered by Alexa when it can not call your skill or when the skill response is invalid.  Please check your endpoint in the skill configuration, verify that your skill is actually called.  If it does, what is the response sent by the skill ?

**Comment by sebsto** [comment]
closing as there is no reply after 50+ days, if you still have still problem, please share more details to help to understand the problem : the skill configuration and lambda configuration in particular.
