### ISSUE TITLE
 Could not find any test files matching pattern: test

### ISSUE THREAD

**Issue by salmanfarisvp** [alexa/skill-sample-nodejs-audio-player#56]
```
cd lambda && npm test

> peaceradio@1.0.0 test D:\Alexa\Pradio\lambda
> mocha

Warning: Could not find any test files matching pattern: test
No test files found
npm ERR! Test failed.  See above for more details.

```
![image](https://user-images.githubusercontent.com/11945360/32571399-4116e16c-c4ed-11e7-914c-f9f5c8979fb0.png)

**Comment by sebsto** [comment]
These instructions are for Linux and Mac, I am not sure how the && will be interpreted on Windows.
It is difficult to debug this without having more details.  
Be sure you are executing this command from the correct directory and  the test directory is present.

**Comment by sebsto** [comment]
I am closing this thread.  Feel free to re-open if you still need assistance.

**Comment by MarvinHannott** [comment]
I have the exact same problem. This is what I run: `"mocha 'out-tsc/src/test/*.js' --reporter min"` 
Because of the project hirachy and compilation through TypeScript, the test folder is inside two other folders. Could that be an issue? 
But recursive search with `"mocha 'out-tsc/**/*.test.js' --recursive --reporter min"` yields the same result, as does the path to a specific test file.

**Comment by sebsto** [comment]
Yes, the instructions in the README are sensitive to the directory layout.  Any different directory layout will require some adjustment.  

Understanding your directory structure is key, you need to make sure both ``mocha`` and ``node`` will find their dependencies.
 
The below command can help
```pwd && ls -R```

We never tested the instructions in the README file against TS.
